/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package guidevelopment;

import java.text.NumberFormat;

/**
 *
 * @author bkling
 */
public class TempConverterWindow extends javax.swing.JFrame {

    /**
     * Creates new form TempConverterWindow
     */
    public TempConverterWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblEnterTemp = new javax.swing.JLabel();
        btnConvertCel = new javax.swing.JButton();
        txtFah = new javax.swing.JTextField();
        lblConvertedTemp = new javax.swing.JLabel();
        txtCel = new javax.swing.JTextField();
        btnConvertFah = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Temperature Converter");

        lblEnterTemp.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblEnterTemp.setForeground(new java.awt.Color(204, 0, 0));
        lblEnterTemp.setText("Fahrenheit:");

        btnConvertCel.setText("Convert to Cel");
        btnConvertCel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConvertCelActionPerformed(evt);
            }
        });

        txtFah.setText("0");

        lblConvertedTemp.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblConvertedTemp.setForeground(new java.awt.Color(204, 0, 0));
        lblConvertedTemp.setText("Celcius:");

        txtCel.setText("0");

        btnConvertFah.setText("Convert to Fah");
        btnConvertFah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConvertFahActionPerformed(evt);
            }
        });

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEnterTemp)
                            .addComponent(lblConvertedTemp))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtFah, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                            .addComponent(txtCel)))
                    .addComponent(btnConvertCel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnConvertFah, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                    .addComponent(btnReset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEnterTemp)
                    .addComponent(txtFah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblConvertedTemp)
                    .addComponent(txtCel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnConvertCel)
                .addGap(18, 18, 18)
                .addComponent(btnConvertFah)
                .addGap(18, 18, 18)
                .addComponent(btnReset)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConvertCelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConvertCelActionPerformed
        // TODO add your handling code here:
        //Convert from Fah to Cel
        String sF = this.txtFah.getText();
        double f = Double.valueOf(sF);
        double c = (f - 32) * 5/9;
        NumberFormat nf = NumberFormat.getNumberInstance();
        nf.setMaximumFractionDigits(2);
        txtCel.setText(nf.format(c));
    }//GEN-LAST:event_btnConvertCelActionPerformed

    private void btnConvertFahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConvertFahActionPerformed
        // TODO add your handling code here:
        //Convert from Cel to Fah
        String sC = this.txtCel.getText();
        double c = Double.valueOf(sC);
        double f = (c * 9/5 + 32);
        NumberFormat nf = NumberFormat.getNumberInstance();
        nf.setMinimumFractionDigits(2);
        txtFah.setText(nf.format(f));
    }//GEN-LAST:event_btnConvertFahActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        //Resets Text Boxs
        txtFah.setText(""+0);
        txtCel.setText(""+0);
    }//GEN-LAST:event_btnResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TempConverterWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TempConverterWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TempConverterWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TempConverterWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TempConverterWindow().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConvertCel;
    private javax.swing.JButton btnConvertFah;
    private javax.swing.JButton btnReset;
    private javax.swing.JLabel lblConvertedTemp;
    private javax.swing.JLabel lblEnterTemp;
    private javax.swing.JTextField txtCel;
    private javax.swing.JTextField txtFah;
    // End of variables declaration//GEN-END:variables
}
